name: .NET Core
on:
  push:
  pull_request:
  release:
    types:
      - published
env:
  # Stop wasting time caching packages
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  # Disable sending usage data to Microsoft
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  PLUGIN_NAME: Lidarr.Plugin.Deemix
  PLUGIN_VERSION: 1.0.0.${{ github.run_number }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.404
      - name: Update Version Info
        run: |
          sed -i'' -e "s/<AssemblyVersion>[0-9.*]\+<\/AssemblyVersion>/<AssemblyVersion>$PLUGINVERSION<\/AssemblyVersion>/g" src/Directory.Build.props
          sed -i'' -e "s/<AssemblyConfiguration>[\$()A-Za-z-]\+<\/AssemblyConfiguration>/<AssemblyConfiguration>${GITHUB_REF#refs/heads/}<\/AssemblyConfiguration>/g" src/Directory.Build.props
      - name: Build net core
        run: dotnet publish src/*.sln -c Release -f netcoreapp3.1
      - name: Upload net core
        uses: actions/upload-artifact@v2
        with:
          name: netcore
          path: ./_plugins/netcoreapp3.1/$PLUGIN_NAME/publish/
